### ISSUE TITLE
Error placing mob, null point exception

### ISSUE THREAD

**Issue by Ayuei** [elBukkit/MagicWorlds#6]
I have the magic plugin enabled, with spigot 1.14.1, there seems to be a problem with mob replacement. I'm using the default configs provided (e.g. dungeon.yml, chest_populator.yml). Is the magicworlds plugin not compatible with 1.14.1?

`[18:43:05] [Server thread/ERROR]: [MagicWorlds] Error replacing mob
java.lang.NullPointerException: null
        at com.elmakers.mine.bukkit.magic.MagicController.inTaggedRegion(MagicController.java:3083) ~[?:?]
        at com.elmakers.mine.bukkit.magicworlds.MagicWorldsController.inTaggedRegion(MagicWorldsController.java:178) ~[?:?]
        at com.elmakers.mine.bukkit.magicworlds.spawn.SpawnRule.process(SpawnRule.java:107) ~[?:?]
        at com.elmakers.mine.bukkit.magicworlds.spawn.MagicSpawnHandler.process(MagicSpawnHandler.java:34) ~[?:?]
        at com.elmakers.mine.bukkit.magicworlds.MagicWorld.processEntitySpawn(MagicWorld.java:126) ~[?:?]
        at com.elmakers.mine.bukkit.magicworlds.listener.EntitySpawnListener.onEntitySpawn(EntitySpawnListener.java:59) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor35.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
        at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:589) ~[spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
        at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:526) ~[spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
        at net.minecraft.server.v1_14_R1.WorldServer.addEntity0(WorldServer.java:934) ~[spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
        at net.minecraft.server.v1_14_R1.WorldServer.addEntity(WorldServer.java:864) ~[spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
        at net.minecraft.server.v1_14_R1.SpawnerCreature.a(SpawnerCreature.java:96) ~[spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
        at net.minecraft.server.v1_14_R1.ChunkProviderServer.lambda$9(ChunkProviderServer.java:412) ~[spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
        at org.bukkit.craftbukkit.libs.it.unimi.dsi.fastutil.longs.Long2ObjectLinkedOpenHashMap$1.forEach(Long2ObjectLinkedOpenHashMap.java:1661) [spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
        at com.google.common.collect.Iterables$UnmodifiableIterable.forEach(Iterables.java:105) [spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
        at net.minecraft.server.v1_14_R1.ChunkProviderServer.tickChunks(ChunkProviderServer.java:364) [spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
        at net.minecraft.server.v1_14_R1.ChunkProviderServer.tick(ChunkProviderServer.java:334) [spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:259) [spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1068) [spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:393) [spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:970) [spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:815) [spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
        at java.lang.Thread.run(Thread.java:834) [?:?]`

**Comment by NathanWolf** [comment]
Does Magic have any errors on startup?

This looks more like an incompatibility with WorldGuard. Are you using WG, and if so is it up to date?

I still can't fully see how it would hit a null at that place in code, though. :|

**Comment by Ayuei** [comment]
I took out all other plugins aside from Magic and MagicWorlds, the problem still persists. 
https://pastebin.com/LHVQQDeP (Full server log from start-up)
http://puu.sh/ElXSx/04908f3df7.zip (MagicWorlds config files)

As a side note, the magic mobs still appear to be spawning (or at least some of)  (e.g. Captain and Warlock), but I'm not sure what this null point exception is referring to.

**Comment by NathanWolf** [comment]
Thank you for all the info!

I think I see where the problem is now. Can you please try out this dev build of Magic? I think it will make that error go away.

http://jenkins.elmakers.com/job/MagicPlugin/2897/com.elmakers.mine.bukkit.plugins$Magic/

**Comment by Ayuei** [comment]
Yup, it fixed it! Thank you.
