### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Keksssii** [elBukkit/MagicWorlds#9]
pls help me,

[13:29:16] [Server thread/INFO]: [MagicWorlds] Enabling MagicWorlds v1.8-SNAPSHOT
[13:29:16] [Server thread/INFO]: [MagicWorlds]   Loading config.yml
[13:29:16] [Server thread/INFO]: [MagicWorlds]   Loading magic
[13:29:16] [Server thread/WARN]: [MagicWorlds] Error loading file magic
java.io.FileNotFoundException: plugins/MagicWorlds/magic (Ist ein Verzeichnis)
	at java.io.FileInputStream.open0(Native Method) ~[?:?]
	at java.io.FileInputStream.open(FileInputStream.java:219) ~[?:?]
	at java.io.FileInputStream.<init>(FileInputStream.java:157) ~[?:?]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:126) ~[server.jar:git-Spigot-a03b1fd-fc318cc]
	at com.elmakers.mine.bukkit.magicworlds.MagicWorldsController.load(MagicWorldsController.java:69) [MagicWorlds-1.8-SNAPSHOT%20(1).jar:?]
	at com.elmakers.mine.bukkit.magicworlds.MagicWorldsController.initialize(MagicWorldsController.java:55) [MagicWorlds-1.8-SNAPSHOT%20(1).jar:?]
	at com.elmakers.mine.bukkit.magicworlds.MagicWorldsPlugin.initialize(MagicWorldsPlugin.java:113) [MagicWorlds-1.8-SNAPSHOT%20(1).jar:?]
	at com.elmakers.mine.bukkit.magicworlds.MagicWorldsPlugin.onEnable(MagicWorldsPlugin.java:105) [MagicWorlds-1.8-SNAPSHOT%20(1).jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) [server.jar:git-Spigot-a03b1fd-fc318cc]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) [server.jar:git-Spigot-a03b1fd-fc318cc]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) [server.jar:git-Spigot-a03b1fd-fc318cc]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:464) [server.jar:git-Spigot-a03b1fd-fc318cc]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:378) [server.jar:git-Spigot-a03b1fd-fc318cc]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:211) [server.jar:git-Spigot-a03b1fd-fc318cc]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784) [server.jar:git-Spigot-a03b1fd-fc318cc]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[13:29:16] [Server thread/INFO]: [MagicWorlds]   Loading real
[13:29:16] [Server thread/WARN]: [MagicWorlds] Error loading file real
java.io.FileNotFoundException: plugins/MagicWorlds/real (Ist ein Verzeichnis)
	at java.io.FileInputStream.open0(Native Method) ~[?:?]
	at java.io.FileInputStream.open(FileInputStream.java:219) ~[?:?]
	at java.io.FileInputStream.<init>(FileInputStream.java:157) ~[?:?]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:126) ~[server.jar:git-Spigot-a03b1fd-fc318cc]
	at com.elmakers.mine.bukkit.magicworlds.MagicWorldsController.load(MagicWorldsController.java:69) [MagicWorlds-1.8-SNAPSHOT%20(1).jar:?]
	at com.elmakers.mine.bukkit.magicworlds.MagicWorldsController.initialize(MagicWorldsController.java:55) [MagicWorlds-1.8-SNAPSHOT%20(1).jar:?]
	at com.elmakers.mine.bukkit.magicworlds.MagicWorldsPlugin.initialize(MagicWorldsPlugin.java:113) [MagicWorlds-1.8-SNAPSHOT%20(1).jar:?]
	at com.elmakers.mine.bukkit.magicworlds.MagicWorldsPlugin.onEnable(MagicWorldsPlugin.java:105) [MagicWorlds-1.8-SNAPSHOT%20(1).jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) [server.jar:git-Spigot-a03b1fd-fc318cc]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) [server.jar:git-Spigot-a03b1fd-fc318cc]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) [server.jar:git-Spigot-a03b1fd-fc318cc]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:464) [server.jar:git-Spigot-a03b1fd-fc318cc]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:378) [server.jar:git-Spigot-a03b1fd-fc318cc]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:211) [server.jar:git-Spigot-a03b1fd-fc318cc]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784) [server.jar:git-Spigot-a03b1fd-fc318cc]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[13:29:16] [Server thread/INFO]: [MagicWorlds]   Loading otherside
[13:29:16] [Server thread/WARN]: [MagicWorlds] Error loading file otherside
java.io.FileNotFoundException: plugins/MagicWorlds/otherside (Ist ein Verzeichnis)
	at java.io.FileInputStream.open0(Native Method) ~[?:?]
	at java.io.FileInputStream.open(FileInputStream.java:219) ~[?:?]
	at java.io.FileInputStream.<init>(FileInputStream.java:157) ~[?:?]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:126) ~[server.jar:git-Spigot-a03b1fd-fc318cc]
	at com.elmakers.mine.bukkit.magicworlds.MagicWorldsController.load(MagicWorldsController.java:69) [MagicWorlds-1.8-SNAPSHOT%20(1).jar:?]
	at com.elmakers.mine.bukkit.magicworlds.MagicWorldsController.initialize(MagicWorldsController.java:55) [MagicWorlds-1.8-SNAPSHOT%20(1).jar:?]
	at com.elmakers.mine.bukkit.magicworlds.MagicWorldsPlugin.initialize(MagicWorldsPlugin.java:113) [MagicWorlds-1.8-SNAPSHOT%20(1).jar:?]
	at com.elmakers.mine.bukkit.magicworlds.MagicWorldsPlugin.onEnable(MagicWorldsPlugin.java:105) [MagicWorlds-1.8-SNAPSHOT%20(1).jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) [server.jar:git-Spigot-a03b1fd-fc318cc]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) [server.jar:git-Spigot-a03b1fd-fc318cc]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) [server.jar:git-Spigot-a03b1fd-fc318cc]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:464) [server.jar:git-Spigot-a03b1fd-fc318cc]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:378) [server.jar:git-Spigot-a03b1fd-fc318cc]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:211) [server.jar:git-Spigot-a03b1fd-fc318cc]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784) [server.jar:git-Spigot-a03b1fd-fc318cc]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[13:29:16] [Server thread/INFO]: [MagicWorlds]   Loading creeper
[13:29:16] [Server thread/WARN]: [MagicWorlds] Error loading file creeper
java.io.FileNotFoundException: plugins/MagicWorlds/creeper (Ist ein Verzeichnis)
	at java.io.FileInputStream.open0(Native Method) ~[?:?]
	at java.io.FileInputStream.open(FileInputStream.java:219) ~[?:?]
	at java.io.FileInputStream.<init>(FileInputStream.java:157) ~[?:?]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:126) ~[server.jar:git-Spigot-a03b1fd-fc318cc]
	at com.elmakers.mine.bukkit.magicworlds.MagicWorldsController.load(MagicWorldsController.java:69) [MagicWorlds-1.8-SNAPSHOT%20(1).jar:?]
	at com.elmakers.mine.bukkit.magicworlds.MagicWorldsController.initialize(MagicWorldsController.java:55) [MagicWorlds-1.8-SNAPSHOT%20(1).jar:?]
	at com.elmakers.mine.bukkit.magicworlds.MagicWorldsPlugin.initialize(MagicWorldsPlugin.java:113) [MagicWorlds-1.8-SNAPSHOT%20(1).jar:?]
	at com.elmakers.mine.bukkit.magicworlds.MagicWorldsPlugin.onEnable(MagicWorldsPlugin.java:105) [MagicWorlds-1.8-SNAPSHOT%20(1).jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) [server.jar:git-Spigot-a03b1fd-fc318cc]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) [server.jar:git-Spigot-a03b1fd-fc318cc]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) [server.jar:git-Spigot-a03b1fd-fc318cc]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:464) [server.jar:git-Spigot-a03b1fd-fc318cc]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:378) [server.jar:git-Spigot-a03b1fd-fc318cc]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:211) [server.jar:git-Spigot-a03b1fd-fc318cc]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784) [server.jar:git-Spigot-a03b1fd-fc318cc]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[13:29:16] [Server thread/INFO]: [MagicWorlds]   Loading mixins
[13:29:16] [Server thread/WARN]: [MagicWorlds] Error loading file mixins
java.io.FileNotFoundException: plugins/MagicWorlds/mixins (Ist ein Verzeichnis)
	at java.io.FileInputStream.open0(Native Method) ~[?:?]
	at java.io.FileInputStream.open(FileInputStream.java:219) ~[?:?]
	at java.io.FileInputStream.<init>(FileInputStream.java:157) ~[?:?]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:126) ~[server.jar:git-Spigot-a03b1fd-fc318cc]
	at com.elmakers.mine.bukkit.magicworlds.MagicWorldsController.load(MagicWorldsController.java:69) [MagicWorlds-1.8-SNAPSHOT%20(1).jar:?]
	at com.elmakers.mine.bukkit.magicworlds.MagicWorldsController.initialize(MagicWorldsController.java:55) [MagicWorlds-1.8-SNAPSHOT%20(1).jar:?]
	at com.elmakers.mine.bukkit.magicworlds.MagicWorldsPlugin.initialize(MagicWorldsPlugin.java:113) [MagicWorlds-1.8-SNAPSHOT%20(1).jar:?]
	at com.elmakers.mine.bukkit.magicworlds.MagicWorldsPlugin.onEnable(MagicWorldsPlugin.java:105) [MagicWorlds-1.8-SNAPSHOT%20(1).jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) [server.jar:git-Spigot-a03b1fd-fc318cc]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) [server.jar:git-Spigot-a03b1fd-fc318cc]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) [server.jar:git-Spigot-a03b1fd-fc318cc]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:464) [server.jar:git-Spigot-a03b1fd-fc318cc]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:378) [server.jar:git-Spigot-a03b1fd-fc318cc]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:211) [server.jar:git-Spigot-a03b1fd-fc318cc]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784) [server.jar:git-Spigot-a03b1fd-fc318cc]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[13:29:16] [Server thread/INFO]: Preparing level "world"
[13:29:16] [Server thread/INFO]: Reloading ResourceManager: Default, bukkit
[13:29:50] [Server thread/INFO]: Loaded 6 recipes

**Comment by NathanWolf** [comment]
I am not sure what's up with this- maybe file permissions?

It looks like you have a few config files (creeper, otherside, real) that the plugin sees but can't load.

Check to make sure the files are readable by the user running your Spigot server.

You may also try renaming them to like "creeper.yml" but that shouldn't matter.

The "real" config I'm pretty sure doesn't work though, so I'd remove that one.
